[package]
name = "vigil-processes"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
vigil-model = { path = "../../core/vigil-model" }
vigil-collect = { path = "../../core/vigil-collect" }
vigil-rules = { path = "../../core/vigil-rules" }
vigil-module = { path = "../../core/vigil-module" }
vigil-view = { path = "../../core/vigil-view" }
serde_json.workspace = true

[dev-dependencies]
vigil-module = { path = "../../core/vigil-module" }
